name: Atletas

on:
  push:
    branches:
      - main
  schedule:
    - cron: 15,45 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  atletas:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: atletas/mercado
      filter: .atletas
      table: atletas
      schema: schemas/atletas.json
