name: atletas

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  atletas:
    uses: ./.github/workflows/extract.yml
    with:
      endpoint: atletas/mercado
      filter: .atletas
      table: atletas
      replace: true