name: Authenticate Google Cloud with OpenID Connect

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/506924123915/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@cartola-data.iam.gserviceaccount.com

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Get current season and round
        id: status
        run: |
          STATUS=$(curl -s https://api.cartola.globo.com/mercado/status)
          echo SEASON=$(echo $STATUS | jq -r '.temporada') >> $GITHUB_OUTPUT
          echo ROUND=$(echo $STATUS | jq -r '.rodada_atual') >> $GITHUB_OUTPUT
      
      - run: echo ${{ steps.status.outputs.STATUS }}-${{ steps.status.outputs.ROUND }}.json
