name: Authenticate Google Cloud with OpenID Connect

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"

jobs:
  auth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url:
          - https://api.cartola.globo.com/atletas/mercado
    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/506924123915/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@cartola-data.iam.gserviceaccount.com

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Compose file path
        id: status
        run: |
          STATUS=$(curl -s https://api.cartola.globo.com/mercado/status)
          SEASON=$(echo $STATUS | jq -r '.temporada')
          ROUND=$(echo $STATUS | jq -r '.rodada_atual')
          ENDPOINT=$(echo "${{ matrix.url }}" | sed 's/https:\/\/api.cartola.globo.com\///')
          echo PATH=$ENDPOINT/$ROUND-$SEASON.json >> $GITHUB_OUTPUT
          
      
      - run: echo ${{ steps.status.outputs.PATH }}
