name: Authenticate Google Cloud with OpenID Connect

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"

jobs:
  auth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        endpoint:
          - atletas/mercado
          - atletas/pontuados/$ROUND
          - clubes
          - mercado/destaques
          - mercado/selecao
          - partidas
    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/506924123915/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@cartola-data.iam.gserviceaccount.com

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Upload to Google Cloud Storage
        run: |
          STATUS=$(curl -s https://api.cartola.globo.com/mercado/status)
          SEASON=$(echo $STATUS | jq -r '.temporada')
          ROUND=$(printf %02d $(echo $STATUS | jq -r '.rodada_atual'))
          PATH=${{ matrix.endpoint }}/$SEASON-$ROUND.json
          curl -s https://api.cartola.globo.com/${{ matrix.endpoint }} -o data.json
          gcloud storage cp data.json gs://cartola/$PATH
