name: Destaques

on:
  push:
    branches:
      - main
  schedule:
    - cron: 15,45 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  destaques:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: mercado/destaques
      filter: .
      table: destaques
      schema: schemas/destaques.json
