name: Esquemas

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 12 * * *

permissions:
  contents: read
  id-token: write

jobs:
  esquemas:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: esquemas
      filter: .
      table: esquemas
      schema: schemas/esquemas.json
