name: Cartola API ETL

on:
  workflow_call:
    inputs:
      endpoint:
        required: true
        type: string
      filter:
        required: true
        type: string
      table:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/506924123915/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@cartola-data.iam.gserviceaccount.com

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Extract from API and load to Google Cloud Storage
        run: |
          # Get current season and round
          STATUS=$(curl -s https://api.cartola.globo.com/mercado/status)
          SEASON=$(echo $STATUS | jq -r '.temporada')
          ROUND=$(echo $STATUS | jq -r '.rodada_atual')
          BASENAME=$(echo $SEASON-$(printf %02d $ROUND))

          # Download and filter data
          curl -s https://api.cartola.globo.com/${{ inputs.endpoint }} | \
            jq ${{ inputs.filter }} | \
            jq --arg S $SEASON --arg R $ROUND 'map(. + {"_temporada": $S, "_rodada": $R})' | \
            jq -c '.[]' > \
            data.json

          # Upload data
          echo gs://cartola/$TARGET_PATH
          gcloud storage cp data.json gs://cartola/${{ inputs.endpoint }}/${{ inputs.table }}/$BASENAME.json

      - name: Load to Google BigQuery from Google Cloud Storage
        run: |
          bq load \
            --autodetect \
            --source_format=NEWLINE_DELIMITED_JSON \
            --replace \
            cartola.${{ inputs.table }} \
            gs://cartola/${{ inputs.endpoint }}/${{ inputs.table }}/*.json