name: Extract from Cartola API

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

permissions:
  contents: "read"
  id-token: "write"

jobs:
  extract:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        endpoint:
          - atletas/mercado
          - atletas/pontuados
          - clubes
          - mercado/destaques
          - mercado/selecao
          - partidas
    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/506924123915/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@cartola-data.iam.gserviceaccount.com

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Extract and load to Google Cloud Storage
        run: |
          SEASON=$(curl -s https://api.cartola.globo.com/mercado/status | jq -r '.temporada')
          ROUND=$(curl -s https://api.cartola.globo.com/mercado/status | jq -r '.rodada_atual' | printf %02d)
          curl -s https://api.cartola.globo.com/${{ matrix.endpoint }} | jq -cS .[] > data.json
          gcloud storage cp data.json gs://cartola/${{ matrix.endpoint }}/$SEASON-$ROUND.json
