name: Extract from Cartola API

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  extract:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - endpoint: atletas/mercado
            filter: .[]
            dir: atletas/mercado/atletas

    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/506924123915/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@cartola-data.iam.gserviceaccount.com

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Extract from API and load to Google Cloud Storage
        run: |
          # Get current season and round
          STATUS=$(curl -s https://api.cartola.globo.com/mercado/status)
          SEASON=$(echo $STATUS | jq -r '.temporada')
          ROUND=$(printf %02d $(echo $STATUS | jq -r '.rodada_atual'))

          # Download and filter data
          curl -s https://api.cartola.globo.com/${{ matrix.endpoint }} | jq -c ${{ matrix.filter }} > data.json

          # Upload data
          echo gs://cartola/$TARGET_PATH
          gcloud storage cp data.json gs://cartola/${{ matrix.dir }}/$SEASON-$ROUND.json
