name: Extract from Cartola API

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  extract:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - endpoint: atletas/mercado
            filter: .atletas

          - endpoint: atletas/pontuados
            filter: .atletas

          - endpoint: mercado/destaques
            filter: .

          - endpoint: partidas
            filter: .partidas

          - endpoint: clubes
            filter: .

          - endpoint: posicoes
            filter: .

          - endpoint: esquemas
            filter: .

    steps:
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/506924123915/locations/global/workloadIdentityPools/github/providers/github
          service_account: github@cartola-data.iam.gserviceaccount.com

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Extract from API and load to Google Cloud Storage
        run: |
          # Get current season and round
          STATUS=$(curl -s https://api.cartola.globo.com/mercado/status)
          SEASON=$(echo $STATUS | jq -r '.temporada')
          ROUND=$(echo $STATUS | jq -r '.rodada_atual')

          # Download and filter data
          curl -s https://api.cartola.globo.com/${{ matrix.endpoint }} | \
            jq ${{ matrix.filter }} | \
            jq --arg S $SEASON --arg R $ROUND 'map(. + {"_temporada": $S, "_rodada": $R})' | \
            jq -c '.[]' > \
            data.json

          # Upload data
          echo gs://cartola/$TARGET_PATH
          gcloud storage cp data.json gs://cartola/${{ matrix.endpoint }}/$SEASON-$(printf %02d $ROUND).json

      - name: Load to Google BigQuery from Google Cloud Storage
        run: |
          # Replace slash with underscore
          TABLE_NAME=$(echo $ENDPOINT | tr '/' '_')
          bq load \
            --autodetect \
            --source_format=NEWLINE_DELIMITED_JSON \
            cartola.$TABLE_NAME \
            gs://cartola/${{ matrix.endpoint }}/*.json