name: Partidas

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  partidas:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: partidas
      filter: .partidas
      table: partidas
