name: Pontuados

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */12 * * *

permissions:
  contents: read
  id-token: write

jobs:
  pontuados:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: atletas/pontuados
      filter: ".atletas | jq 'to_entries | map({atleta_id: .key} + .value)'"
      table: pontuados
      schema: schemas/pontuados.json
