name: Pontuados

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  pontuados:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: atletas/pontuados
      filter: .atletas
      table: pontuados
