name: Posições

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 12 * * *

permissions:
  contents: read
  id-token: write

jobs:
  posicoes:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: posicoes
      filter: .
      table: posicoes
      schema: schemas/posicoes.json
