name: Status

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  atletas:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: atletas/mercado
      filter: .status
      table: status
